[book]
authors = ["Viliam Vadocz"]
language = "en"
multilingual = false
src = "src"
title = "The Volpe Programming Language"

[output.html]
theme = "src/theme"
default-theme = "ayu"
preferred-dark-theme = "ayu"
